spring.application.name=submission_portal
logging.level.org.springframework.security=DEBUG


server.forward-headers-strategy=native
server.servlet.session.tracking-modes=cookie

# PostgreSQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Supabase Configuration
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket.name=${SUPABASE_BUCKET_NAME}

# Disable HTTP Client Auto-Configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.http.client.HttpClientAutoConfiguration

# Gmail SMTP Configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
mail.from=noreply@assignmentportal.live
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000


# OTP Configuration
otp.expiry.minutes=1
